twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: "Les Fleurs de Riton"
        fb_pixel: ""
        google_maps: 'XXX'
        gtm: 'XXX'
        recaptcha_public: ''
        recaptcha_private: ''
        mailjet_public: ''
        mailjet_private: ''
        posts_img_directory: '/uploads/images/posts'

when@test:
    twig:
        strict_variables: true
