name: Déploiement en production

on:
  push:
    branches:
      - Test  # Changer en la branche sur laquelle vous souhaitez déployer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Déploiement SFTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: home633537587.1and1-data.host
        username: u85588472
        password: ${{ secrets.SFTP_PASSWORD }}  # Définissez le mot de passe SFTP comme secret dans les paramètres du dépôt
        port: 22
        protocol: ftps
        local-dir: "./"  # Chemin vers votre projet Symfony local
        server-dir: "/portfolio/projets/lesfleursderiton"  # Chemin vers le répertoire de déploiement sur le serveur de production
      
